- hosts: tags_SurojitRakshit
  gather_facts: False
  become: yes
  vars:
    source_file: ./index.html
    dest_file: /var/www/html
    ansible_user: ec2-user 
    ansible_ssh_private_key_file: /home/ec2-user/environment/Final_Project/Ansible/FinalProject
  tasks:
    - name: Install Apache Web Server
      yum: name=httpd state=latest
      when: ansible_os_family == "RedHat"
      
    - name: Install Apache Web Server
      package: name=httpd state=latest
      when: ansible_os_family == "Amazon"
    
    - name: Print Linux Family
      debug: var=ansible_os_family
      
    - name: Copy index.html
      copy: src={{ source_file }} dest={{ dest_file }} mode=0555
      notify: Restart Apache
      
    - name: Start Apache Web Server
      service: name=httpd state=started enabled=yes
      
    - shell: /usr/bin/uptime
      register: result
      
    - name: Print result variable
      debug: 
        var: result
    
    - name: Print debug message
      debug: 
        msg: "The result was {{ result }}"
      
    
  handlers:
    - name: Restart Apache
      service: name=httpd state=restarted